######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 25 12:54:55 2013
######################################################################

TEMPLATE = app
TARGET = quit
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
