######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 25 12:54:35 2013
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
